############################################################################################################
#  This includes all DynamoDb resources
#
#  Grants Table - This table stores all code grants on a ttl. If a code grant is not retrieved before
#  expiration, they will be automatically removed.
#
############################################################################################################
Resources:

  GrantsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      GlobalSecondaryIndexes:
      KeySchema:
        - KeyType: HASH
          AttributeName: code
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: grants
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
