############################################################################################################
#
#  Attached to each lambda function
#
############################################################################################################
environment:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  NODE_OPTIONS: "--enable-source-maps"
  STAGE: ${self:custom.stage}
  GRANTS_TABLE: grants
  KMS_COGNITO_ALIAS: alias/${self:custom.cognito.kmsId}
  COGNITO_POOL_ID: !Ref CognitoUserPool
  COGNITO_REFRESH_TOKEN_EXPIRES_DAYS: ${self:custom.cognito.refreshTokenExpirationInDays}
  
