environment:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  NODE_OPTIONS: "--enable-source-maps"
  SVC_NAME: ${self:service}
  STAGE: ${self:custom.stage}
  REGION: ${self:provider.region}
  GRANTS_TABLE: grants
  KMS_COGNITO_ALIAS: alias/${self:custom.cognito.kmsId}
  COGNITO_POOL_ID: !Ref CognitoUserPool
  COGNITO_REFRESH_TOKEN_EXPIRES_DAYS: ${self:custom.cognito.refreshTokenExpirationInDays}

